[package]
name = "csv2rdf"
version = "0.1.1"
authors = ["bharath181 <bharathselvaraj18@gmail.com>", "Greg Hanson <g.isaac.hanson@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"
description = "Library for converting a CSV file to N-Triple RDF"
repository = "https://github.com/DeciSym/csv2rdf"
readme = "README.md"
keywords = ["csv", "rdf", "semantic-web", "converter", "parser"]
categories = ["command-line-utilities", "encoding", "parser-implementations", "science", "web-programming"]

[dependencies]
clap = { version = "4.6", features = ["derive","cargo"] }
convert_case = "0.11"
csv = "1.4"
log = "0.4"
oxrdf = "0.3"
oxrdfio = "0.2"
